spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/housekeeper?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: housekeeper
    password: lafin1234
logging:
  level:
    org.hibernate.SQL: debug