create table hk_auth (
     id bigint generated by default as identity,
     access_token varchar(255),
     created_at timestamp,
     expired_at timestamp,
     refresh_token varchar(255),
     primary key (id)
);

create table hk_house (
      id bigint generated by default as identity,
      created_at timestamp,
      name varchar(255),
      type varchar(255),
      updated_at timestamp,
      user_id bigint,
      primary key (id)
);

create table hk_room (
     id bigint generated by default as identity,
     created_at timestamp,
     house_id bigint,
     name varchar(255),
     status varchar(255),
     updated_at timestamp,
     user_id bigint,
     primary key (id)
);

create table hk_stuff (
      id bigint generated by default as identity,
      amount float not null,
      created_at timestamp,
      name varchar(255),
      room_id bigint,
      status varchar(255),
      unit varchar(255),
      updated_at timestamp,
      user_id bigint,
      primary key (id)
);

create table hk_user (
     id bigint generated by default as identity,
     created_at timestamp,
     email varchar(255),
     nickname varchar(255),
     password varchar(255),
     status varchar(255),
     type varchar(255),
     updated_at timestamp,
     primary key (id)
);